<a href="https://colab.research.google.com/github/leonistor/ml-manning/blob/master/basics-ml-stack/ML_Stack_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML Stack: NumPy

In [0]:
import numpy as np

## List vs Array

In [17]:
L = list(range(1,6)); L

[1, 2, 3, 4, 5]

In [19]:
A = np.array(range(1,6)); A

array([1, 2, 3, 4, 5])

In [20]:
L2 = [x ** 2 for x in L]; L2

[1, 4, 9, 16, 25]

In [21]:
A ** 2

array([ 1,  4,  9, 16, 25])

In [22]:
np.log(A)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [23]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

## Product

In [24]:
a = np.array([1,2])
b = np.array([2,1])
a * b

array([2, 2])

In [25]:
np.sum(a*b)

4

In [27]:
(a * b).sum()

4

In [29]:
# produs vectorial
np.dot(a, b)

4

In [31]:
a.dot(b) == b.dot(a)

True

In [33]:
a @ b

4

## Norm (magnitude)

In [35]:
a_magnitude = np.sqrt((a*a).sum()); a_magnitude

2.23606797749979

In [38]:
a_magnitude = np.linalg.norm(a); a_magnitude

2.23606797749979

## Angle

In [40]:
cosangle = a.dot(b) / ( np.linalg.norm(a) * np.linalg.norm(b) ); cosangle

0.7999999999999998

In [41]:
angle = np.arccos(cosangle); angle # radians

0.6435011087932847

## Matrices

In [43]:
# first index is row, second is column
M = np.array([ [1, 2], [3, 4] ]); M

array([[1, 2],
       [3, 4]])

In [44]:
L = [ [1, 2], [3, 4] ]; L

[[1, 2], [3, 4]]

In [46]:
# indexing
L[0][0]

1

In [47]:
M[0][0]

1

In [49]:
# better
M[0,0]

1

In [0]:
# not recommended; use array
M2 = np.matrix([ [1, 2], [3, 4] ])

In [51]:
A = np.array(M2); A

array([[1, 2],
       [3, 4]])

In [52]:
# transpose
A.T

array([[1, 3],
       [2, 4]])

## Generate arrays / matrices

In [53]:
Z = np.zeros(10); Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
Z = np.zeros((5,5)); Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
O = np.ones((5,5)); O

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
# uniform distributed
R = np.random.random((5,5)); R

array([[0.0636336 , 0.16412874, 0.6645665 , 0.94385374, 0.01318042],
       [0.5403159 , 0.99083917, 0.06652885, 0.22323996, 0.35815542],
       [0.55295205, 0.84180299, 0.78150036, 0.53611829, 0.17490893],
       [0.97003217, 0.94050663, 0.50880255, 0.12364348, 0.23474916],
       [0.75648592, 0.50212069, 0.45698888, 0.22275248, 0.85845408]])

In [62]:
# gaussian (standard normal) distributed; no tuple!
G = np.random.randn(5, 5); G

array([[ 1.89913861, -0.41862341, -0.44797463,  0.06081647, -0.62607902],
       [ 0.843663  , -0.49081424,  0.24834272, -0.61505648,  0.0637491 ],
       [-2.19957295, -0.25442353, -0.26169486, -1.83174878,  0.62662605],
       [ 0.45753949,  0.1403184 ,  0.94911523, -0.94035891, -1.85989745],
       [ 0.23764391, -0.43608194, -0.1613585 ,  1.46114893,  0.52660222]])

In [63]:
# mean, variance
G.mean()

-0.12115922330594676

In [64]:
G.var()

0.8914250928783045

## Matrix operations

In [0]:
# * is element by element mult
# dot is matrix mult

In [66]:
# inverse
A = np.array([ [1, 2], [3, 4] ])
Ainv = np.linalg.inv(A); Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
Ainv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [69]:
# determinant
np.linalg.det(A)

-2.0000000000000004

In [70]:
# diagonal
np.diag(A)

array([1, 4])

In [71]:
# diagonal matrix
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [72]:
a = np.array([1, 2])
b = np.array([3, 4])

# outer product
np.outer(a, b)

array([[3, 4],
       [6, 8]])

In [73]:
# inner product
np.inner(a, b)

11

In [74]:
a.dot(b)

11

In [75]:
# trace: sum of diagonal
np.diag(A).sum()

5

In [76]:
np.trace(A)

5

## Eigenvalues, eigenvectors

In [81]:
# 100 samples of 3 features
X = np.random.randn(100, 3)

# covariance of 3 features
cov = np.cov(X.T)
cov

array([[ 1.09611853, -0.02627582, -0.05899847],
       [-0.02627582,  0.98518463, -0.01019996],
       [-0.05899847, -0.01019996,  0.89519682]])

In [83]:
# eigenvalues and eigenvectors
np.linalg.eig(cov)

(array([1.11612545, 0.87652269, 0.98385185]),
 array([[ 0.95367121, -0.27360565, -0.12510466],
        [-0.17215322, -0.15526407, -0.97275708],
        [-0.24672758, -0.94922759,  0.19517297]]))

## Solve a linear system

In [84]:
# Ax = B
# solution: x = inverse(A) x B
A

array([[1, 2],
       [3, 4]])

In [0]:
B = np.array([3, 4])

In [88]:
X = np.linalg.inv(A).dot(B); X

array([-2. ,  2.5])

In [90]:
# solve; use this!
X = np.linalg.solve(A, B); X

array([-2. ,  2.5])

In [92]:
# problem:
# X1 + X2 = 2200
# 1.5 * X1 + 4 * X2 = 5050
A = np.array([[1,1], [1.5,4]])
B = np.array([2200, 5050])
np.linalg.solve(A, B)

array([1500.,  700.])